#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc wm -O HDMI-1 eDP-1

bspc monitor HDMI-1 -d I II III IV V VI VII VIII
bspc monitor eDP-1 -d IX X

bspc config border_width         1
bspc config window_gap           8
bspc config top_padding 	24  # 24 is equal to polybar's height

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false

bspc rule -a discord desktop='^8'
bspc rule -a zathura state=tiled
