#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

#bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8
bspc monitor eDP1 -d 9 10

bspc config border_width         1
bspc config window_gap           8
bspc config top_padding 	24  # 24 is equal to polybar's height

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false

bspc rule -a discord desktop='^8'
bspc rule -a zathura state=tiled
